version: '3.1'
services:
  new_gen:
    container_name: new_gen
    build: 
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8001:8000