# Generated by Django 5.0.1 on 2024-02-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_remove_patient_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='diagnnosis',
            new_name='diagnosis',
        ),
    ]
